__version__ = "0.0.1"

SQL_SERVER = ...
SQL_DATABASE = ...

# TODO make these global secrets read from a local config file or a DB table with the secure data within it or from the future bitwarden api container

API_AUTH_URL = ...
API_TOKEN = ...
API_SECRET = ...
API_BASE_URL = ...

ACCOUNT_NUMBER = ...
ROUTING_NUMBER = ...

